name: .NET Packages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
      - name: Build package
        run: dotnet build --no-restore
      - name: Test package
        run: dotnet test --no-build --verbosity normal
      - name: Pack package
        run: dotnet pack src/Move.Common/*.csproj --configuration Release
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: nugetPackage
          path: src/Move.Common/bin/Release/ 
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: nugetPackage
      - name: Push package to GitHub Packages
        run: dotnet nuget push nugetPackage/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/soonthana/index.json